/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SimplePortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BodyPortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            label?: string;
            url?: string;
            nofollow?: boolean;
            _type: "citation";
            _key: string;
          }
        | {
            href?: string;
            _type: "internalLink";
            _key: string;
          }
        | {
            href?: string;
            blank?: boolean;
            _type: "externalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type NavItem = {
  _type: "navItem";
  label?: string;
  href?: string;
  external?: boolean;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalOverride?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noindex?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organizationName?: string;
  legalName?: string;
  email?: string;
  foundingDate?: string;
  sameAs?: Array<string>;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  nav?: Array<
    {
      _key: string;
    } & NavItem
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: string;
  description?: string;
  seo?: Seo;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type BlogCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogCategory";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: BodyPortableText;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  author?: AuthorReference;
  reviewer?: AuthorReference;
  blogCategory?: BlogCategoryReference;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  publishedAt?: string;
  updatedAt?: string;
  faq?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  seo?: Seo;
};

export type BlogCategory = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  legacyId?: string;
  role?: string;
  jobTitle?: string;
  bio?: SimplePortableText;
  credentials?: Array<string>;
  email?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sameAs?: Array<string>;
  knowsAbout?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SimplePortableText
  | SanityImageAssetReference
  | BodyPortableText
  | NavItem
  | FaqItem
  | Seo
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Tag
  | AuthorReference
  | BlogCategoryReference
  | TagReference
  | Post
  | BlogCategory
  | Slug
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true]  | order(publishedAt desc) {      _id,  title,  "slug": slug.current,  excerpt,  "category": blogCategory->title,  "categorySlug": blogCategory->slug.current,  "tags": tags[]->slug,  "tagTitles": tags[]->title,  "authorId": author->slug.current,  "authorSlug": author->slug.current,  "reviewerId": reviewer->slug.current,  publishedAt,  updatedAt,  heroImage,  "noindex": coalesce(seo.noindex, false)  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  category: string | null;
  categorySlug: string | null;
  tags: Array<string | null> | null;
  tagTitles: Array<string | null> | null;
  authorId: string | null;
  authorSlug: string | null;
  reviewerId: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  noindex: boolean | false;
}>;

// Source: sanity/lib/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post"]  | order(publishedAt desc) {      _id,  title,  "slug": slug.current,  excerpt,  "category": blogCategory->title,  "categorySlug": blogCategory->slug.current,  "tags": tags[]->slug,  "tagTitles": tags[]->title,  "authorId": author->slug.current,  "authorSlug": author->slug.current,  "reviewerId": reviewer->slug.current,  publishedAt,  updatedAt,  heroImage,  "noindex": coalesce(seo.noindex, false),    body  }
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  category: string | null;
  categorySlug: string | null;
  tags: Array<string | null> | null;
  tagTitles: Array<string | null> | null;
  authorId: string | null;
  authorSlug: string | null;
  reviewerId: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  noindex: boolean | false;
  body: BodyPortableText | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    excerpt,    body,    heroImage,    faq,    seo,    publishedAt,    updatedAt,    "category": blogCategory->title,    "categorySlug": blogCategory->slug.current,    "tags": tags[]->slug,    "tagTitles": tags[]->title,    "author": author->{  _id,  name,  "slug": slug.current,  legacyId,  role,  jobTitle,  bio,  credentials,  email,  avatar,  sameAs,  knowsAbout},    "reviewer": reviewer->{  _id,  name,  "slug": slug.current,  legacyId,  role,  jobTitle,  bio,  credentials,  email,  avatar,  sameAs,  knowsAbout}  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  body: BodyPortableText | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  faq: Array<
    {
      _key: string;
    } & FaqItem
  > | null;
  seo: Seo | null;
  publishedAt: string | null;
  updatedAt: string | null;
  category: string | null;
  categorySlug: string | null;
  tags: Array<string | null> | null;
  tagTitles: Array<string | null> | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    legacyId: string | null;
    role: string | null;
    jobTitle: string | null;
    bio: SimplePortableText | null;
    credentials: Array<string> | null;
    email: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    sameAs: Array<string> | null;
    knowsAbout: Array<string> | null;
  } | null;
  reviewer: {
    _id: string;
    name: string | null;
    slug: string | null;
    legacyId: string | null;
    role: string | null;
    jobTitle: string | null;
    bio: SimplePortableText | null;
    credentials: Array<string> | null;
    email: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    sameAs: Array<string> | null;
    knowsAbout: Array<string> | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true]{    "slug": slug.current  }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: AUTHORS_QUERY
// Query: *[_type == "author"] | order(name asc) {      _id,  name,  "slug": slug.current,  legacyId,  role,  jobTitle,  bio,  credentials,  email,  avatar,  sameAs,  knowsAbout  }
export type AUTHORS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  legacyId: string | null;
  role: string | null;
  jobTitle: string | null;
  bio: SimplePortableText | null;
  credentials: Array<string> | null;
  email: string | null;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  sameAs: Array<string> | null;
  knowsAbout: Array<string> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: AUTHOR_BY_SLUG_QUERY
// Query: *[_type == "author" && (slug.current == $slug || legacyId == $slug)][0] {      _id,  name,  "slug": slug.current,  legacyId,  role,  jobTitle,  bio,  credentials,  email,  avatar,  sameAs,  knowsAbout  }
export type AUTHOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  legacyId: string | null;
  role: string | null;
  jobTitle: string | null;
  bio: SimplePortableText | null;
  credentials: Array<string> | null;
  email: string | null;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  sameAs: Array<string> | null;
  knowsAbout: Array<string> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: BLOG_CATEGORIES_QUERY
// Query: *[_type == "blogCategory"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    seo  }
export type BLOG_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  seo: Seo | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: TAGS_QUERY
// Query: *[_type == "tag"] | order(title asc) {    _id,    title,    slug,    description,    seo  }
export type TAGS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  seo: Seo | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] {    organizationName,    legalName,    email,    foundingDate,    sameAs,    defaultOgImage,    nav  }
export type SITE_SETTINGS_QUERY_RESULT = {
  organizationName: string | null;
  legalName: string | null;
  email: string | null;
  foundingDate: string | null;
  sameAs: Array<string> | null;
  defaultOgImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  nav: Array<
    {
      _key: string;
    } & NavItem
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POSTS_BY_AUTHOR_QUERY
// Query: *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true && author->slug.current == $slug]  | order(publishedAt desc) {      _id,  title,  "slug": slug.current,  excerpt,  "category": blogCategory->title,  "categorySlug": blogCategory->slug.current,  "tags": tags[]->slug,  "tagTitles": tags[]->title,  "authorId": author->slug.current,  "authorSlug": author->slug.current,  "reviewerId": reviewer->slug.current,  publishedAt,  updatedAt,  heroImage,  "noindex": coalesce(seo.noindex, false)  }
export type POSTS_BY_AUTHOR_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  category: string | null;
  categorySlug: string | null;
  tags: Array<string | null> | null;
  tagTitles: Array<string | null> | null;
  authorId: string | null;
  authorSlug: string | null;
  reviewerId: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  noindex: boolean | false;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_BY_CATEGORY_QUERY
// Query: *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true && lower(blogCategory->slug.current) == lower($category)]  | order(publishedAt desc) {      _id,  title,  "slug": slug.current,  excerpt,  "category": blogCategory->title,  "categorySlug": blogCategory->slug.current,  "tags": tags[]->slug,  "tagTitles": tags[]->title,  "authorId": author->slug.current,  "authorSlug": author->slug.current,  "reviewerId": reviewer->slug.current,  publishedAt,  updatedAt,  heroImage,  "noindex": coalesce(seo.noindex, false)  }
export type POSTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  category: string | null;
  categorySlug: string | null;
  tags: Array<string | null> | null;
  tagTitles: Array<string | null> | null;
  authorId: string | null;
  authorSlug: string | null;
  reviewerId: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  noindex: boolean | false;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_BY_TAG_QUERY
// Query: *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true && $tag in tags[]->slug]  | order(publishedAt desc) {      _id,  title,  "slug": slug.current,  excerpt,  "category": blogCategory->title,  "categorySlug": blogCategory->slug.current,  "tags": tags[]->slug,  "tagTitles": tags[]->title,  "authorId": author->slug.current,  "authorSlug": author->slug.current,  "reviewerId": reviewer->slug.current,  publishedAt,  updatedAt,  heroImage,  "noindex": coalesce(seo.noindex, false)  }
export type POSTS_BY_TAG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  category: string | null;
  categorySlug: string | null;
  tags: Array<string | null> | null;
  tagTitles: Array<string | null> | null;
  authorId: string | null;
  authorSlug: string | null;
  reviewerId: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  noindex: boolean | false;
}>;

// Source: sanity/lib/queries.ts
// Variable: TOOL_BLOG_LINKS_QUERY
// Query: *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true && slug.current in $slugs][0] {    title,    "slug": slug.current,    excerpt  }
export type TOOL_BLOG_LINKS_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  excerpt: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true]\n  | order(publishedAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  "category": blogCategory->title,\n  "categorySlug": blogCategory->slug.current,\n  "tags": tags[]->slug,\n  "tagTitles": tags[]->title,\n  "authorId": author->slug.current,\n  "authorSlug": author->slug.current,\n  "reviewerId": reviewer->slug.current,\n  publishedAt,\n  updatedAt,\n  heroImage,\n  "noindex": coalesce(seo.noindex, false)\n\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post"]\n  | order(publishedAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  "category": blogCategory->title,\n  "categorySlug": blogCategory->slug.current,\n  "tags": tags[]->slug,\n  "tagTitles": tags[]->title,\n  "authorId": author->slug.current,\n  "authorSlug": author->slug.current,\n  "reviewerId": reviewer->slug.current,\n  publishedAt,\n  updatedAt,\n  heroImage,\n  "noindex": coalesce(seo.noindex, false)\n,\n    body\n  }\n': ALL_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    body,\n    heroImage,\n    faq,\n    seo,\n    publishedAt,\n    updatedAt,\n    "category": blogCategory->title,\n    "categorySlug": blogCategory->slug.current,\n    "tags": tags[]->slug,\n    "tagTitles": tags[]->title,\n    "author": author->{\n  _id,\n  name,\n  "slug": slug.current,\n  legacyId,\n  role,\n  jobTitle,\n  bio,\n  credentials,\n  email,\n  avatar,\n  sameAs,\n  knowsAbout\n},\n    "reviewer": reviewer->{\n  _id,\n  name,\n  "slug": slug.current,\n  legacyId,\n  role,\n  jobTitle,\n  bio,\n  credentials,\n  email,\n  avatar,\n  sameAs,\n  knowsAbout\n}\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true]{\n    "slug": slug.current\n  }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "author"] | order(name asc) {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  legacyId,\n  role,\n  jobTitle,\n  bio,\n  credentials,\n  email,\n  avatar,\n  sameAs,\n  knowsAbout\n\n  }\n': AUTHORS_QUERY_RESULT;
    '\n  *[_type == "author" && (slug.current == $slug || legacyId == $slug)][0] {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  legacyId,\n  role,\n  jobTitle,\n  bio,\n  credentials,\n  email,\n  avatar,\n  sameAs,\n  knowsAbout\n\n  }\n': AUTHOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "blogCategory"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    seo\n  }\n': BLOG_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "tag"] | order(title asc) {\n    _id,\n    title,\n    slug,\n    description,\n    seo\n  }\n': TAGS_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    organizationName,\n    legalName,\n    email,\n    foundingDate,\n    sameAs,\n    defaultOgImage,\n    nav\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true && author->slug.current == $slug]\n  | order(publishedAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  "category": blogCategory->title,\n  "categorySlug": blogCategory->slug.current,\n  "tags": tags[]->slug,\n  "tagTitles": tags[]->title,\n  "authorId": author->slug.current,\n  "authorSlug": author->slug.current,\n  "reviewerId": reviewer->slug.current,\n  publishedAt,\n  updatedAt,\n  heroImage,\n  "noindex": coalesce(seo.noindex, false)\n\n  }\n': POSTS_BY_AUTHOR_QUERY_RESULT;
    '\n  *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true && lower(blogCategory->slug.current) == lower($category)]\n  | order(publishedAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  "category": blogCategory->title,\n  "categorySlug": blogCategory->slug.current,\n  "tags": tags[]->slug,\n  "tagTitles": tags[]->title,\n  "authorId": author->slug.current,\n  "authorSlug": author->slug.current,\n  "reviewerId": reviewer->slug.current,\n  publishedAt,\n  updatedAt,\n  heroImage,\n  "noindex": coalesce(seo.noindex, false)\n\n  }\n': POSTS_BY_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true && $tag in tags[]->slug]\n  | order(publishedAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  "category": blogCategory->title,\n  "categorySlug": blogCategory->slug.current,\n  "tags": tags[]->slug,\n  "tagTitles": tags[]->title,\n  "authorId": author->slug.current,\n  "authorSlug": author->slug.current,\n  "reviewerId": reviewer->slug.current,\n  publishedAt,\n  updatedAt,\n  heroImage,\n  "noindex": coalesce(seo.noindex, false)\n\n  }\n': POSTS_BY_TAG_QUERY_RESULT;
    '\n  *[_type == "post" && defined(publishedAt) && coalesce(seo.noindex, false) != true && slug.current in $slugs][0] {\n    title,\n    "slug": slug.current,\n    excerpt\n  }\n': TOOL_BLOG_LINKS_QUERY_RESULT;
  }
}
